
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b"\x95\\\x86\x12.\x90\xf8V\xef\xb7<'N\x08\x92,"
    
_lr_action_items = {'COMMENT':([0,1,2,4,6,7,9,11,12,13,14,15,16,17,18,19,21,22,23,24,25,28,29,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[1,-25,1,-22,-3,-4,-24,1,-23,-19,-20,-15,1,1,1,1,-5,-6,-21,1,-13,-16,-11,1,1,-12,-14,1,1,-9,1,-7,-26,1,-10,-8,-17,-27,]),'RPAR':([1,2,4,9,12,13,14,15,16,23,25,26,28,29,34,35,38,40,43,44,45,],[-25,-18,-22,-24,-23,-19,-20,-15,25,-21,-13,35,-16,-11,-12,-14,-9,-7,-10,-8,-17,]),'STATEMENT':([0,1,2,4,6,7,8,9,10,11,12,13,14,15,16,17,18,19,21,22,23,24,25,28,29,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[2,-25,2,-22,-3,-4,18,-24,19,2,-23,-19,-20,-15,2,2,2,2,-5,-6,-21,2,-13,-16,-11,2,2,-12,-14,2,2,-9,2,-7,-26,2,-10,-8,-17,-27,]),'ENDMARKER':([0,1,2,4,6,7,9,11,12,13,14,15,21,22,23,25,28,29,34,35,38,40,43,44,45,],[3,-25,-18,-22,-3,-4,-24,20,-23,-19,-20,-15,-5,-6,-21,-13,-16,-11,-12,-14,-9,-7,-10,-8,-17,]),'DEDENT':([1,2,4,9,12,13,14,15,23,25,28,29,34,35,38,40,41,42,43,44,45,46,],[-25,-18,-22,-24,-23,-19,-20,-15,-21,-13,-16,-11,-12,-14,-9,-7,-26,45,-10,-8,-17,-27,]),'INDENT':([27,],[36,]),'NEWLINE':([0,1,2,4,6,7,9,11,12,13,14,15,17,21,22,23,24,25,28,29,31,33,34,35,37,38,39,40,43,44,45,],[6,-25,14,-22,-3,-4,-24,21,-23,23,-20,-15,27,-5,-6,-21,27,-13,-16,-11,27,27,-12,-14,27,-9,27,-7,-10,-8,-17,]),'DEF':([0,1,2,4,6,7,9,11,12,13,14,15,16,17,18,19,21,22,23,24,25,28,29,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[10,-25,10,-22,-3,-4,-24,10,-23,-19,-20,-15,10,10,10,10,-5,-6,-21,10,-13,-16,-11,10,10,-12,-14,10,10,-9,10,-7,-26,10,-10,-8,-17,-27,]),'LPAR':([2,18,19,],[16,16,16,]),'$end':([3,5,20,],[-1,0,-2,]),'COLON':([1,2,4,9,12,13,14,15,18,19,23,25,28,29,30,32,34,35,38,40,43,44,45,],[-25,17,-22,-24,-23,24,-20,-15,31,33,-21,-13,-16,-11,37,39,-12,-14,-9,-7,-10,-8,-17,]),'CLASS':([0,1,2,4,6,7,9,11,12,13,14,15,16,17,18,19,21,22,23,24,25,28,29,31,33,34,35,36,37,38,39,40,41,42,43,44,45,46,],[8,-25,8,-22,-3,-4,-24,8,-23,-19,-20,-15,8,8,8,8,-5,-6,-21,8,-13,-16,-11,8,8,-12,-14,8,8,-9,8,-7,-26,8,-10,-8,-17,-27,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'stmt':([0,2,11,16,17,18,19,24,31,33,36,37,39,42,],[7,15,22,26,28,15,15,28,28,28,41,28,28,46,]),'conddef':([0,2,11,16,17,18,19,24,31,33,36,37,39,42,],[9,9,9,9,9,9,9,9,9,9,9,9,9,9,]),'suite_plus':([36,],[42,]),'suite':([17,24,31,33,37,39,],[29,34,38,40,43,44,]),'funcdef':([0,2,11,16,17,18,19,24,31,33,36,37,39,42,],[4,4,4,4,4,4,4,4,4,4,4,4,4,4,]),'file_input_star':([0,],[11,]),'classdef':([0,2,11,16,17,18,19,24,31,33,36,37,39,42,],[12,12,12,12,12,12,12,12,12,12,12,12,12,12,]),'args':([2,18,19,],[13,30,32,]),'file_input':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> file_input","S'",1,None,None,None),
  ('file_input -> ENDMARKER','file_input',1,'p_file_input','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',13),
  ('file_input -> file_input_star ENDMARKER','file_input',2,'p_file_input','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',14),
  ('file_input_star -> NEWLINE','file_input_star',1,'p_file_input_star','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',25),
  ('file_input_star -> stmt','file_input_star',1,'p_file_input_star','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',26),
  ('file_input_star -> file_input_star NEWLINE','file_input_star',2,'p_file_input_star','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',27),
  ('file_input_star -> file_input_star stmt','file_input_star',2,'p_file_input_star','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',28),
  ('funcdef -> DEF STATEMENT COLON suite','funcdef',4,'p_funcdef','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',40),
  ('funcdef -> DEF STATEMENT args COLON suite','funcdef',5,'p_funcdef','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',41),
  ('classdef -> CLASS STATEMENT COLON suite','classdef',4,'p_classdef','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',50),
  ('classdef -> CLASS STATEMENT args COLON suite','classdef',5,'p_classdef','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',51),
  ('conddef -> STATEMENT COLON suite','conddef',3,'p_conddef','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',60),
  ('conddef -> STATEMENT args COLON suite','conddef',4,'p_conddef','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',61),
  ('args -> LPAR RPAR','args',2,'p_args','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',67),
  ('args -> LPAR stmt RPAR','args',3,'p_args','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',68),
  ('args -> stmt','args',1,'p_args','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',69),
  ('suite -> stmt','suite',1,'p_suite','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',80),
  ('suite -> NEWLINE INDENT suite_plus DEDENT','suite',4,'p_suite','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',81),
  ('stmt -> STATEMENT','stmt',1,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',92),
  ('stmt -> STATEMENT args','stmt',2,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',93),
  ('stmt -> STATEMENT NEWLINE','stmt',2,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',94),
  ('stmt -> STATEMENT args NEWLINE','stmt',3,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',95),
  ('stmt -> funcdef','stmt',1,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',96),
  ('stmt -> classdef','stmt',1,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',97),
  ('stmt -> conddef','stmt',1,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',98),
  ('stmt -> COMMENT','stmt',1,'p_stmt','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',99),
  ('suite_plus -> stmt','suite_plus',1,'p_suite_plus','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',110),
  ('suite_plus -> suite_plus stmt','suite_plus',2,'p_suite_plus','C:\\Users\\Lubo\\workspace2\\Parsing\\MyParser1.py',111),
]
